.\" Manpage for nuseradd.
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH man 1 "10 Apr 2021" "gerenciamento de sistema de arquivo simples - FAT-16 manpage "
.SH NAME
Simulador de gerenciamento de sistema de arquivo simples com baseada na tabela de alocação de 16 bits - FAT 16
.SH SYNOPSIS
\ ./scr/shell
.SH DESCRIPTION 

.SH OPTIONS
Nao a necessidade de passar argumentos, pois todo o gerenciamente e feito dentro do shell criado para esse trabalho.
.SH SHELL OPTIONS

help 			            		 Imprime Ajuda ao usuario.

init			            		 Inicializar o sistema de arquivos.  

load 					             Carregar o sistema de arquivos do disco.   

ls   					             Lista diretório.

mkdir 					             Cria diretório.

create 					             Cria arquivo.

unlink 					             Excluir arquivo ou diretório. 

write \"string\"  					 Escrever dados em um arquivo.

append \"string\" 					 Anexar dados em um arquivo.

read  				            	 Lê o conteúdo de um arquivo.

exit 				                 Sai do simulador.
.SH BUGS
Ate o momento nao existe bugs conhecidos.
.SH AUTHOR

Lucas Rômulo de Souza Resende (srlucasromulo@github)

Alex de Andrade Soares (alexandrades@github)

Sidney de Oliveira Felipe Júnior (sidney-junior@github)
